Location CRUD
Ideas2IT/cimpar-backend pull request #102
Opened 2024-10-28 18:07 UTC by MonishaSivanathan

- Implemented CRUD for location module
- handled logger and exception

2024-10-29 06:21 UTC, tamsud requested changes

2024-10-29 06:21 UTC, tamsud commented on routes/location_routes.py
> +@router.get("/active/location")
what is the use of fetching the active loaction?

2024-10-29 06:21 UTC, tamsud commented on routes/location_routes.py
> +@router.get("/active/location")
why we need a seperate api for that?

2024-10-29 06:25 UTC, MonishaSivanathan commented on routes/location_routes.py
> +@router.get("/active/location")
we have 2 screen, in admin screen we have to disply all the active and inactive colomns, with pagination. where in make appointment screen have to fetch all the active data with out pagination . thats why i wrote seperate API.

2024-10-29 07:35 UTC, tamsud commented on routes/location_routes.py
> +@router.get("/active/location")
you can have query param in the get all api and filter out in case of active = true
there is no need for the separate api right?

2024-10-30 05:47 UTC, tamsud approved these changes

2024-10-30 05:47 UTC, merged