Fix - location Model
Ideas2IT/cimpar-backend pull request #104
Opened 2024-11-04 07:57 UTC by MonishaSivanathan

- changed the location Model got working day colomn

2024-11-04 09:06 UTC, tamsud requested changes

2024-11-04 09:06 UTC, tamsud commented on controller/location_controller.py
> -                        "daysOfWeek": [loc.working_days],
there is a mismatch in create and update fucntion.
Update:
                hoursOfOperation=[
                    {
                        "daysOfWeek": [loc.working_days],
Create:

  "daysOfWeek": loc.working_days,

2024-11-04 15:53 UTC, tamsud requested changes

2024-11-04 15:53 UTC, tamsud commented on controller/location_controller.py
> +                params.append(".status$contains=active")
why are you checking contains here as you know if its true than we can check for string 'active' right?
Which means its a whole string i dont think contains required here. can you validate and add the full string check?

2024-11-04 15:53 UTC, tamsud commented on controller/location_controller.py
> +            if not active or center_name or address:
why pagination at a certain check?

2024-11-04 15:53 UTC, tamsud commented on controller/location_controller.py
> +            endpoint = "/Location?" + "&".join(params)
what would happen if params is empty list will the endpoint work ? have you validated? if yes can you provide the screenshot here?
url : '/Location?' -> it will cretate a endpoint like this incase of empty string, its not a correct way to form the url. can you check and re-write

2024-11-04 15:53 UTC, tamsud commented on controller/location_controller.py
> -                logger.error(f"Error {location_response.status_code}: {location_response.json()}")
what is the reason for removing the logger?

2024-11-04 15:53 UTC, tamsud commented on controller/location_controller.py
> +            if not active or center_name or address:
why pagination at a certain check?

2024-11-04 15:53 UTC, tamsud commented on controller/master_controller.py
> +            if master_data and not master_data[0]['is_active']:
master_data[0]['is_active']: -> validate before accessing it.

2024-11-04 15:53 UTC, tamsud commented on controller/master_controller.py
> +                raise Exception("Unable to create")
can you raise the proper exception? update method right?

2024-11-04 15:53 UTC, tamsud commented on controller/master_controller.py
> +                content=f"Failed to create: {str(e)}")
can you raise the proper exception? update method right?

2024-11-04 15:53 UTC, tamsud commented on controller/master_controller.py
> +                raise Exception("Unable to create")
If possible add the table name as well, unable to update the which master data/ like / location/lab/ etc...

2024-11-04 15:53 UTC, tamsud commented on controller/master_controller.py
> +                raise Exception("Unable to create")
If possible add the table name as well, unable to update the which master data/ like / location/lab/ etc...

2024-11-04 15:53 UTC, tamsud commented on controller/master_controller.py
>                      raise Exception("Unable to update")
If possible add the table name as well, unable to update the which master data/ like / location/lab/ etc...

2024-11-04 15:53 UTC, tamsud commented on controller/master_controller.py
>                  raise Exception("Unable to update")
If possible add the table name as well, unable to update the which master data/ like / location/lab/ etc...

2024-11-04 15:53 UTC, tamsud commented on routes/master_routers.py
> +    all_records: Optional[bool] = "",
DO not give empty string for Boolean unless its necessary? make it false as a default

2024-11-05 09:57 UTC, MonishaSivanathan commented on controller/location_controller.py
> -                        "daysOfWeek": [loc.working_days],
changed in update function

2024-11-05 09:58 UTC, MonishaSivanathan commented on controller/location_controller.py
> +                params.append(".status$contains=active")
removed the contains and checked with the direct value

2024-11-05 09:58 UTC, MonishaSivanathan commented on controller/location_controller.py
> +            if not active or center_name or address:
only for notactive, centername, address need pagination. for active colomn we dont want pagination

2024-11-05 09:59 UTC, MonishaSivanathan commented on controller/location_controller.py
> +            endpoint = "/Location?" + "&".join(params)
![Screenshot from 2024-11-05 13-00-47](https://github.com/user-attachments/assets/1f21c9e1-b8e4-4777-b65c-0e742ed003ff)

2024-11-05 10:01 UTC, MonishaSivanathan commented on controller/location_controller.py
> +            endpoint = "/Location?" + "&".join(params)
if we didnt give data mean it will fetch all the value with pagination

2024-11-05 10:01 UTC, MonishaSivanathan commented on controller/location_controller.py
> -                logger.error(f"Error {location_response.status_code}: {location_response.json()}")
added logger

2024-11-05 10:01 UTC, MonishaSivanathan commented on controller/location_controller.py
> +            if not active or center_name or address:
only for center name, address, active colomn pagination required

2024-11-05 10:02 UTC, MonishaSivanathan commented on controller/master_controller.py
> +            if master_data and not master_data[0]['is_active']:
validated and raised now

2024-11-05 10:03 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                raise Exception("Unable to create")
added for update method and added the table

2024-11-05 10:03 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                content=f"Failed to create: {str(e)}")
raised proper exception

2024-11-05 10:04 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                raise Exception("Unable to create")
added table name in the exception

2024-11-05 10:04 UTC, MonishaSivanathan commented on controller/master_controller.py
>                      raise Exception("Unable to update")
added table name in the exception

2024-11-05 11:01 UTC, MonishaSivanathan commented on controller/location_controller.py
> +            endpoint = "/Location?" + "&".join(params)
url : '/Location?' This Url will never form in any scenario

2024-11-05 11:14 UTC, MonishaSivanathan commented on routes/master_routers.py
> +    all_records: Optional[bool] = "",
changed to false as default

2024-11-05 11:16 UTC, Vigneshanbumani0101 approved these changes

2024-11-05 11:18 UTC, merged