Fix-Location-Delete
Ideas2IT/cimpar-backend pull request #111
Opened 2024-11-21 11:44 UTC by MonishaSivanathan

- fix location delete

2024-12-02 07:58 UTC, tamsud requested changes

2024-12-02 07:58 UTC, tamsud commented on controller/location_controller.py
>      def delete_location(resource_id: str, loc: LocationDeleteModel):
If its delete API then it should do only the delete/soft delete.?
Why are we taking the status from the user?
Either modify the API to status_update/change the functionality to handle only delete (inactive/cancelled).

2024-12-02 13:51 UTC, tamsud requested changes

2024-12-02 13:51 UTC, tamsud commented on routes/location_routes.py
>  @permission_required("LOCATION", "DELETE")
Using DELETE permission for an update operation is not good practice.

2024-12-02 14:15 UTC, MonishaSivanathan commented on controller/location_controller.py
>      def delete_location(resource_id: str, loc: LocationDeleteModel):
changed the permission tamil

2024-12-02 14:15 UTC, MonishaSivanathan commented on routes/location_routes.py
>  @permission_required("LOCATION", "DELETE")
changed into update @tamsud

2024-12-03 06:18 UTC, tamsud approved these changes

2024-12-03 06:18 UTC, merged