FIX-Transcation-appointment
Ideas2IT/cimpar-backend pull request #112
Opened 2024-11-28 09:35 UTC by MonishaSivanathan

- added function to get get_by_id in appointment
- added repayment transaction
- added functions to fetch multiple display for the display
- added payment routes, added a constant value

2024-11-28 13:14 UTC, tamsud requested changes

2024-11-28 13:14 UTC, tamsud commented on controller/appointment_controller.py
> +                "amount": app.total_cost*100,
why are we multiplying by 100?

2024-11-28 13:14 UTC, tamsud commented on controller/payment_controller.py
> +            from controller.appointment_controller import AppointmentClient
can you add the proper comment why are we adding the impoer inside the function? like it should call actual aidbox API instead of our one.

2024-11-28 13:14 UTC, tamsud commented on routes/payment_routes.py
> +    return PaymentClient.intent_initiate(appointment_id, payment)
Here, do we need to check the list of payments that are there for the same appointment, and do we need to mark it as failure or something?
In which case we need to allow the user to re-initiate the payment for the same appoointment?

2024-11-28 13:20 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +                "amount": app.total_cost*100,
1 dollar is equal to 100 cents , the amount we are passing taken as cent so we multiplying 100 to convert dolar

2024-11-28 13:23 UTC, tamsud commented on controller/payment_controller.py
> +            from controller.appointment_controller import AppointmentClient
as # proper comment

2024-11-28 13:33 UTC, MonishaSivanathan commented on routes/payment_routes.py
> +    return PaymentClient.intent_initiate(appointment_id, payment)
its not payment detail tamil, im getting mail id from user, if payment has time out. if used closed the tab and opening against thats why payment has re initiated

2024-12-02 07:58 UTC, tamsud requested changes

2024-12-02 07:58 UTC, tamsud commented on controller/payment_controller.py
> +            from controller.appointment_controller import AppointmentClient
add a proper intentation

2024-12-02 07:58 UTC, tamsud commented on controller/payment_controller.py
> +            if appointment_id:
is appointment_id and patient_id both are mandatory? update the code accordingly

2024-12-02 07:58 UTC, tamsud commented on models/payment_validation.py
> +    email: str
Add a generic email validation?

2024-12-02 07:58 UTC, tamsud commented on routes/payment_routes.py
>  async def payment_success(request: Request, status: str, resource_id: str):
update payment success to proper function name

2024-12-02 07:58 UTC, tamsud commented on routes/payment_routes.py
> +@router.get("/payment/filter")
url name should be proper, remove the filter form the url?

2024-12-03 06:23 UTC, tamsud requested changes

2024-12-03 06:23 UTC, tamsud commented on models/payment_validation.py
> +    email: EmailStr
No email validation added yet

2024-12-03 06:23 UTC, tamsud commented on controller/payment_controller.py
> +        if payment_status == "cancelled":
This is not correct? what would happen is there is not previous payment for the appointment?

2024-12-03 07:09 UTC, merged