Transaction CRUD
Ideas2IT/cimpar-backend pull request #115
Opened 2024-12-04 05:45 UTC by MonishaSivanathan

- Added get function for transaction
- Added get by id function
- Added custom query function
- Added a extract function to extract the fields

2024-12-04 13:21 UTC, tamsud requested changes

2024-12-04 13:21 UTC, tamsud commented on routes/transaction_routes.py
> +@router.get("/transaction/detail")
can you move this to get all itself

2024-12-04 13:21 UTC, tamsud commented on controller/transaction_controller.py
> +        csv_output = BytesIO()
Why are we using ByteIO for csv?

2024-12-04 13:21 UTC, tamsud commented on controller/transaction_controller.py
> +            f.write(csv_output.getvalue())
why we need to store the file?

2024-12-04 13:21 UTC, tamsud commented on controller/transaction_controller.py
> +            TransactionClient.delete_file(filename)
why we need to delete the csv?

2024-12-04 14:52 UTC, MonishaSivanathan commented on routes/transaction_routes.py
> +@permission_required("TRANSACTION", "READ")
changed to ALL_READ permission

2024-12-04 14:53 UTC, MonishaSivanathan commented on controller/transaction_controller.py
> +        csv_output = BytesIO()
To store the file in memory and and remove

2024-12-04 14:54 UTC, MonishaSivanathan commented on controller/transaction_controller.py
> +            f.write(csv_output.getvalue())
without storing cant return

2024-12-05 06:45 UTC, tamsud commented on controller/transaction_controller.py
> +            TransactionClient.delete_file(filename)
why we need to store and delete incase if its already in memory

2024-12-05 08:56 UTC, MonishaSivanathan commented on controller/transaction_controller.py
> +        csv_output = BytesIO()
@tamsud i have removed the function and im not storing any where, im generating the on the flow and return

2024-12-05 08:56 UTC, MonishaSivanathan commented on controller/transaction_controller.py
> +            f.write(csv_output.getvalue())
no @tamsud im not storing

2024-12-05 08:57 UTC, MonishaSivanathan commented on controller/transaction_controller.py
> +            TransactionClient.delete_file(filename)
i have changed tamil, im not storing

2024-12-05 12:15 UTC, tamsud approved these changes

2024-12-05 12:15 UTC, merged