Fix-ServiceHistory
Ideas2IT/cimpar-backend pull request #116
Opened 2024-12-04 10:59 UTC by MonishaSivanathan

- fixed service history get_all function

2024-12-04 13:43 UTC, tamsud requested changes

2024-12-04 13:43 UTC, tamsud commented on controller/appointment_controller.py
> +            if extract_data:
No need to add the multiple loop for incase just need to extend the result for some condition.

2024-12-05 06:49 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +            if extract_data:
@tamsud  i have changed it and re pushed

2024-12-05 07:01 UTC, tamsud approved these changes

2024-12-05 07:01 UTC, merged