Payment Changes
Ideas2IT/cimpar-backend pull request #117
Opened 2024-12-10 12:33 UTC by MonishaSivanathan

- change the payment changes for update
- changed the put method to post method
- added new API to get the payment status

2024-12-11 13:28 UTC, tamsud requested changes

2024-12-11 13:28 UTC, tamsud commented on controller/payment_controller.py
> +            client_secret = response.get("object").get("client_secret")
What would happen if the object itself is not there?

2024-12-11 13:28 UTC, tamsud commented on controller/payment_controller.py
> +                    .get("reference").split("/")[-1]
check the length before taking the values using index position

2024-12-11 18:55 UTC, MonishaSivanathan commented on controller/payment_controller.py
> +            client_secret = response.get("object").get("client_secret")
i have handled it @tamsud

2024-12-11 18:56 UTC, MonishaSivanathan commented on controller/payment_controller.py
> +                    .get("reference").split("/")[-1]
checked the index nd picked the values, change the logic accordingly

2024-12-12 10:08 UTC, tamsud requested changes

2024-12-12 10:08 UTC, tamsud commented on controller/payment_controller.py
> +                if len(patient_reference) > 0:
why are you checking the length of the dict?

2024-12-12 10:08 UTC, tamsud commented on controller/payment_controller.py
> +                if len(appointment_reference) >= 0:
why are you checking the length of the dict?

2024-12-12 10:36 UTC, MonishaSivanathan commented on controller/payment_controller.py
> +                if len(patient_reference) > 0:
i have checked the splited @tamsud

2024-12-12 11:07 UTC, tamsud approved these changes

2024-12-12 11:07 UTC, merged