Fix-bug02-phase02
Ideas2IT/cimpar-backend pull request #122
Opened 2024-12-18 12:26 UTC by MonishaSivanathan

- updated time in payment colomn
- changed the payment status
- changed the colomn names in csv download function

2024-12-18 13:15 UTC, MonishaSivanathan commented on controller/transaction_controller.py
> +            payment_status = entry["payment_reconciliation_resource"]["status"]
this key will definitely come @tamsud, thats why im accessing

2024-12-18 14:16 UTC, tamsud requested changes

2024-12-18 14:16 UTC, tamsud commented on controller/transaction_controller.py
> +            payment_status = entry["payment_reconciliation_resource"]["status"]
are you getting it from 3rd party api or form DB query?

2024-12-18 14:31 UTC, MonishaSivanathan commented on controller/transaction_controller.py
> +            payment_status = entry["payment_reconciliation_resource"]["status"]
from DB query @tamsud

2024-12-19 07:07 UTC, tamsud approved these changes

2024-12-19 07:07 UTC, merged