Router Changes
Ideas2IT/cimpar-backend pull request #14
Opened 2024-06-24 13:19 UTC by MonishaSivanathan

- in router changes the routes
- done some changes in delete function

2024-06-24 13:25 UTC, tamsud commented on routes/encounter_routes.py
>  async def get_encounter(patient_id: str, request: Request):
encounter id is not used inside the function

2024-06-24 13:26 UTC, tamsud commented on routes/encounter_routes.py
> +@router.get("/encounter/{encounter_id}")
why get all comes with encounter_id

2024-06-24 13:27 UTC, tamsud commented on routes/encounter_routes.py
>  async def update_encounter(patient_id: str, encounter: EncounterUpdateModel, request: Request):
why encounter model used here

2024-06-24 13:27 UTC, tamsud commented on routes/encounter_routes.py
> +async def delete_encounter(patient_id: str, encounter_id:str, request: Request):
where is the check for is encounter alrady exist for particular patient or not?

2024-06-24 13:28 UTC, tamsud commented on routes/insurance_routes.py
>  async def get_insurance_by_patient_id(patient_id: str, request: Request):
insuracnce id is not used inside the fucntion

2024-06-24 13:29 UTC, tamsud commented on routes/medication_routes.py
>      logger.info(f"Updated Medication: {updated_medication}")
only patient id used here , why there is no medication id in the fucntion

2024-06-25 09:12 UTC, tamsud requested changes

2024-06-25 09:12 UTC, tamsud commented on controller/insurance_controller.py
> +    def update_by_patient_id(patient_id: str, insurance_id: str, updated_coverage: CoverageUpdateModel):
rename this function as it required module id

2024-06-25 10:59 UTC, MonishaSivanathan commented on routes/encounter_routes.py
>  async def update_encounter(patient_id: str, encounter: EncounterUpdateModel, request: Request):
changed

2024-06-25 11:00 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +    def update_by_patient_id(patient_id: str, insurance_id: str, updated_coverage: CoverageUpdateModel):
renamed

2024-06-25 11:00 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +    def delete_by_patient_id(patient_id: str, encounter_id: str):
renamed

2024-06-25 11:01 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +            if coverage["id"] == insurance_id and coverage["beneficiary"]["reference"] == f"Patient/{patient_id}":
changed using get method

2024-06-25 11:01 UTC, MonishaSivanathan commented on controller/medication_controller.py
> +    def update_medication_by_patient_id(patient_id: str, med:MedicationUpdateModel):
its not posiible, i will leave as it is

2024-06-25 11:51 UTC, tamsud requested changes

2024-06-25 11:51 UTC, tamsud commented on controller/encounter_controller.py
> +            encounter = Encounter.make_request(method="GET", endpoint=f"/fhir/Encounter/{encounter_id}?subject=Patient/{patient_id}")
Will it give response only for the status code == 200 ?

just checking the encounter will work?

2024-06-25 11:51 UTC, tamsud commented on controller/encounter_controller.py
> +            if existing_encounter["subject"]["reference"] == f"Patient/{patient_id}":
will subject and referance always come in the response.?
what would happen incase of no entries in DB?

2024-06-25 13:02 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            encounter = Encounter.make_request(method="GET", endpoint=f"/fhir/Encounter/{encounter_id}?subject=Patient/{patient_id}")
no it will give 404 for that i have handled

2024-06-25 13:03 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            if existing_encounter["subject"]["reference"] == f"Patient/{patient_id}":
no entry it will raise exception no record found

2024-06-25 13:07 UTC, tamsud requested changes

2024-06-25 13:07 UTC, tamsud commented on controller/encounter_controller.py
> +            encounter = Encounter.make_request(method="GET", endpoint=f"/fhir/Encounter/{encounter_id}?subject=Patient/{patient_id}")
can you attach the screenshot here for the 404 error.  (endpoint: endpoint=f"/fhir/Encounter/{encounter_id}?subject=Patient/{patient_id}")
1.in Rest_coslole in AIDBOX. 
2. in Code

2024-06-25 13:10 UTC, tamsud requested changes

2024-06-25 13:10 UTC, tamsud commented on controller/hl7_immunization_controller.py
>              if not response_immunization:
why its not solved yet?check my previous comment

2024-06-25 13:10 UTC, tamsud commented on controller/insurance_controller.py
> +            if response_coverage.status_code == 404:
Need screenshot for the same using aidbox console

2024-06-25 13:10 UTC, tamsud commented on controller/insurance_controller.py
>              existing_coverage = response_coverage.json() if response_coverage else {}
what is the fix here or exising code work without issue?

2024-06-25 13:22 UTC, MonishaSivanathan commented on controller/hl7_immunization_controller.py
> +            response_immunization = Immunization.make_request(method="GET", endpoint=f"/fhir/Immunization/{immunization_id}?patient=Patient/{patient_id}")
![Uploading Screenshot from 2024-06-25 18-43-13.png…]()

2024-06-25 13:24 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +            response_coverage = Coverage.make_request(method = "GET", endpoint= f"/fhir/Coverage/{insurance_id}?beneficiary=Patient/{patient_id}")
![Uploading Screenshot from 2024-06-25 18-53-44.png…]()
![Screenshot from 2024-06-25 18-53-44](https://github.com/Ideas2IT/cimpar-backend/assets/114001736/9a72f4bf-578f-487e-b1ef-8021baac7afc)

2024-06-25 13:25 UTC, MonishaSivanathan commented on controller/hl7_immunization_controller.py
> +            response_immunization = Immunization.make_request(method="GET", endpoint=f"/fhir/Immunization/{immunization_id}?patient=Patient/{patient_id}")
![Uploading Screenshot from 2024-06-25 18-43-13.png…]()

2024-06-25 13:25 UTC, MonishaSivanathan commented on controller/hl7_immunization_controller.py
> +            response_immunization = Immunization.make_request(method="GET", endpoint=f"/fhir/Immunization/{immunization_id}?patient=Patient/{patient_id}")
![Screenshot from 2024-06-25 18-43-13](https://github.com/Ideas2IT/cimpar-backend/assets/114001736/73db4333-5ba6-4e2b-87d0-a4e39ee9409b)

2024-06-25 13:28 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +            if response_coverage.status_code == 404:
![Screenshot from 2024-06-25 18-53-44](https://github.com/Ideas2IT/cimpar-backend/assets/114001736/62206a4f-be0b-46dd-b100-10a1d3775796)

2024-06-25 13:28 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +            if response_coverage.status_code == 404:
i have added screen shot for the above 404

2024-06-25 13:29 UTC, MonishaSivanathan commented on controller/hl7_immunization_controller.py
>              if not response_immunization:
i have checked and added screen shot below

2024-06-25 13:41 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            if existing_encounter["subject"]["reference"] == f"Patient/{patient_id}" and existing_encounter['id'] == encounter_id:
if the record present it will subject and reference, if not it will raise exception "No immunization found"

2024-06-25 13:43 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            encounter = Encounter.make_request(method="GET", endpoint=f"/fhir/Encounter/{encounter_id}?subject=Patient/{patient_id}")
![Screenshot from 2024-06-25 18-43-13](https://github.com/Ideas2IT/cimpar-backend/assets/114001736/6f6445c1-f0cf-4805-aa55-23c6ddea6276)

2024-06-25 15:17 UTC, MonishaSivanathan commented on routes/encounter_routes.py
> +@router.get("/encounter/{encounter_id}")
changed

2024-06-25 15:19 UTC, MonishaSivanathan commented on routes/encounter_routes.py
> +@router.get("/encounter/{encounter_id}")
for modeule_id i have added and changed after

2024-06-26 07:38 UTC, tamsud requested changes

2024-06-26 07:38 UTC, tamsud commented on controller/encounter_controller.py
> +            else:
After verifying the condition and providing the response, there's no need for an else statement. If the condition isn't met, the following code will be executed regardless, so the unnecessary conditional check can be removed.

2024-06-26 07:38 UTC, tamsud commented on controller/encounter_controller.py
> +            else:
After verifying the condition and providing the response, there's no need for an else statement. If the condition isn't met, the following code will be executed regardless, so the unnecessary conditional check can be removed.

2024-06-26 07:38 UTC, tamsud commented on controller/encounter_controller.py
> +            else:
After verifying the condition and providing the response, there's no need for an else statement. If the condition isn't met, the following code will be executed regardless, so the unnecessary conditional check can be removed.

2024-06-26 07:38 UTC, tamsud commented on controller/insurance_controller.py
> +            else:
After verifying the condition and providing the response, there's no need for an else statement. If the condition isn't met, the following code will be executed regardless, so the unnecessary conditional check can be removed.

2024-06-26 07:38 UTC, tamsud commented on controller/insurance_controller.py
> +            else:
After verifying the condition and providing the response, there's no need for an else statement. If the condition isn't met, the following code will be executed regardless, so the unnecessary conditional check can be removed.

2024-06-26 07:38 UTC, tamsud commented on controller/insurance_controller.py
> +            else:
After verifying the condition and providing the response, there's no need for an else statement. If the condition isn't met, the following code will be executed regardless, so the unnecessary conditional check can be removed.

2024-06-26 07:52 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            else:
removed the else stamenent, returned

2024-06-26 07:52 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            else:
removed the else stamenent, returned

2024-06-26 07:52 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +            else:
removed the else stamenent, returned

2024-06-26 07:52 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +            else:
removed the else stamenent, returned

2024-06-26 07:52 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +            else:
removed the else stamenent, returned

2024-06-26 07:54 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            else:
removed the else stamenent, returned

2024-06-26 07:56 UTC, tamsud commented on controller/encounter_controller.py
> +            else:
have you removed here?

2024-06-26 08:43 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            else:
i have removed

2024-06-26 08:43 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            else:
yes i have removed

2024-06-26 12:13 UTC, merged