Fixed Medication Update Issue
Ideas2IT/cimpar-backend pull request #23
Opened 2024-07-08 14:59 UTC by MonishaSivanathan

- changed the optional field
- changed the logic for update and hadled all scenario

2024-07-09 06:36 UTC, tamsud requested changes

2024-07-09 06:36 UTC, tamsud commented on controller/medication_controller.py
>              else:
here i think we need to make it as a elif, need clarfication. can you expalin all the scenarios

2024-07-09 06:36 UTC, tamsud commented on controller/medication_controller.py
>              else:
same here

2024-07-09 10:42 UTC, MonishaSivanathan commented on controller/medication_controller.py
>              else:
i have changed

2024-07-09 10:42 UTC, MonishaSivanathan commented on controller/medication_controller.py
>              else:
changed

2024-07-10 10:56 UTC, tamsud approved these changes

2024-07-10 11:01 UTC, merged