Develop pre
Ideas2IT/cimpar-backend pull request #34
Opened 2024-07-16 07:43 UTC by rajasekari2i

2024-07-19 12:18 UTC, tamsud requested changes

2024-07-19 12:18 UTC, tamsud commented on controller/medication_controller.py
> +            result["is_other_medication_exist"] = True
will it be true always or when it become  false

2024-07-19 12:18 UTC, tamsud commented on controller/medication_controller.py
> +            result["is_current_medication_exist"] = True
will it be true always or when it become false

2024-07-19 12:18 UTC, tamsud commented on controller/patient_controller.py
> +            # if not pat.createAccount:
why code is commented out here

2024-07-19 12:18 UTC, tamsud commented on controller/patient_controller.py
> +            if patients.get('total', 1) == 0:
why default is 1

2024-07-19 12:18 UTC, tamsud commented on controller/service_history_controller.py
> +            if lab_result and not immunization:
can you explain:

            if lab_result and not immunization:
                if not service_history:  
                    return []
                else:
                    return ServiceHistoryClient.process_lab_result(service_history)

            if immunization and not lab_result:
                if not immuzation:  
                    return []
                else:
                    return ServiceHistoryClient.process_immunization(immuzation)

2024-07-19 12:18 UTC, tamsud commented on models/encounter_validation.py
> +    return f"+1{phone_number}"
why are we hardcoding +1 while return the ph number

2024-07-19 12:18 UTC, tamsud commented on models/patient_validation.py
>  def validate_phone_number(phone_number: str) -> str:
models/encounter_validation.py same fucntion there in two places

remove one of them

2024-07-19 12:18 UTC, tamsud commented on routes/appointment_routes.py
> +        all_appointment: Optional[bool] = None,
why we need all_appointment boolean? by default we can go with all appointment right

2024-09-12 08:10 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +                start=app.date_of_appointment,
changed it

2024-09-12 08:10 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            if encounters.get('total', 1) == 0:
changed the default

2024-09-12 08:11 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +            primary_insurance = CoverageWrapper if from_patient else Coverage
now changed that to single variable and used it

2024-09-12 08:11 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +                if primary_coverage_result.get('is_primary_insurance_exist') is True:
changed the condition

2024-09-12 08:11 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +                if primary_coverage_result.get('is_primary_insurance_exist') is False and ins_plan.insurance_type == "primary":
changed the condition

2024-09-12 08:12 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +                if secondary_coverage_result.get('is_secondary_insurance_exist') is True:
changed the condition

2024-09-12 08:12 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +                if secondary_coverage_result.get('is_secondary_insurance_exist') is False and ins_plan.insurance_type == "secondary":
changed the condition

2024-09-12 08:12 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +            result["created"] = True
if its created mean we will return created = true. i kept it as common

2024-09-12 08:13 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +                if response_coverage.status_code == 404:
changed, firstly checking the validation and put this logic

2024-09-12 08:13 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +                if response_coverage.status_code == 404:
changed, firstly checking the validation and put this logic

2024-09-12 08:14 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +                if primary_coverage_result.get('is_primary_insurance_exist') is True:
changed the condition

2024-09-12 08:14 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +                if secondary_coverage_result.get('is_secondary_insurance_exist') is True:
changed the condition

2024-09-12 08:14 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +                if secondary_coverage_result.get('is_secondary_insurance_exist') is False and updated_coverage.insurance_type== "secondary":
changed the condition

2024-09-12 08:14 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +                if tertiary_coverage_result.get('is_tertiary_insurance_exist') is False and updated_coverage.insurance_type== "tertiary":
changed the condition

2024-09-12 08:15 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +            if beneficiary_id == patient_id:
just checking both the id is same

2024-09-12 08:17 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +        insurance_status = "active" if coverage.haveInsurance else "draft"
removed one field and kept only the status

2024-09-12 08:17 UTC, MonishaSivanathan commented on controller/insurance_controller.py
> +        result = PRIMARY_STATUS if updated_coverage.insurance_type == "primary" else SECONDARY_STATUS \
changed and checked with lower()

2024-09-12 08:17 UTC, MonishaSivanathan commented on controller/lab_result_controller.py
> +            if lab_result.get('total', 1) == 0:
changed the default value

2024-09-12 08:17 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                 "ethnicity": "CimparEthnicity", "company" : "CimparInsuranceCompany"}
updated

2024-09-12 08:25 UTC, MonishaSivanathan commented on controller/medication_controller.py
> +            result["is_current_medication_exist"] = True
remoed the condition

2024-09-12 08:25 UTC, MonishaSivanathan commented on controller/patient_controller.py
> +            # if not pat.createAccount:
removed the code

2024-09-12 08:25 UTC, MonishaSivanathan commented on controller/patient_controller.py
> +            if patients.get('total', 1) == 0:
changed the default value

2024-09-12 08:26 UTC, MonishaSivanathan commented on controller/service_history_controller.py
> +            if lab_result and not immunization:
we have removed the code and moved to aidbox query

2024-09-12 08:26 UTC, MonishaSivanathan commented on models/encounter_validation.py
> +    return f"+1{phone_number}"
removed the hard coded value

2024-09-12 08:27 UTC, MonishaSivanathan commented on models/patient_validation.py
>  def validate_phone_number(phone_number: str) -> str:
changed the function and have imported from patient_validation

2024-09-19 09:17 UTC, tamsud approved these changes

2024-09-19 12:31 UTC, merged