Service Layer Refactoring
Ideas2IT/cimpar-backend pull request #7
Opened 2024-06-07 13:56 UTC by MonishaSivanathan

- removed the service layer
- routed the request directly to the controller

2024-06-12 08:06 UTC, tamsud requested changes

2024-06-12 08:06 UTC, tamsud commented on controller/encounter_controller.py
> +            encounters = API.do_request(method = "GET", endpoint= f"/fhir/Encounter")
try get from base

2024-06-12 08:06 UTC, tamsud commented on controller/hl7_immunization_controller.py
> +            response_immunization = API.do_request(method = "GET", endpoint= "/fhir/Immunization")
update the aidbox package to the latest version.
And use the make_request instead of do_request

2024-06-12 09:18 UTC, tamsud requested changes

2024-06-12 09:18 UTC, tamsud commented on controller/patient_controller.py
> +        try:
Is that all parameters are mandatory?

2024-06-12 09:18 UTC, tamsud commented on routes/medication_routes.py
> +def get_medication_by_patient_id(patient_id: str):
In router change all the API calls to the async fucntions

2024-06-12 09:18 UTC, tamsud commented on routes/medication_routes.py
> +    return MedicationClient.update_medication_by_patient_id(patient_id, updated_medication)
<img width="565" alt="image" src="https://github.com/Ideas2IT/cimpar-backend/assets/106092208/4f16683d-38fc-48a1-9da4-2025c06cbbc3">
<img width="565" alt="image" src="https://github.com/Ideas2IT/cimpar-backend/assets/106092208/4f16683d-38fc-48a1-9da4-2025c06cbbc3">
fucntion is expecting only one argument why two arguments are passed into it

2024-06-12 12:47 UTC, MonishaSivanathan commented on controller/encounter_controller.py
> +            encounters = API.do_request(method = "GET", endpoint= f"/fhir/Encounter")
i have got from base and changed the code

2024-06-12 12:47 UTC, MonishaSivanathan commented on controller/hl7_immunization_controller.py
> +            response_immunization = API.do_request(method = "GET", endpoint= f"/fhir/Immunization/?patient=Patient/{patient_id}")
i have got from base and changed the do_request to make_request

2024-06-12 12:48 UTC, MonishaSivanathan commented on controller/patient_controller.py
> +        try:
it is not i have removed it.

2024-06-12 12:49 UTC, MonishaSivanathan commented on routes/medication_routes.py
> +def get_medication_by_patient_id(patient_id: str):
i have changed to async function

2024-06-12 12:49 UTC, MonishaSivanathan commented on routes/medication_routes.py
> +    return MedicationClient.update_medication_by_patient_id(patient_id, updated_medication)
sorry, i have resolved it.

2024-06-13 06:03 UTC, tamsud approved these changes

2024-06-13 06:03 UTC, merged