Master data load
Ideas2IT/cimpar-backend pull request #75
Opened 2024-08-22 10:25 UTC by MonishaSivanathan

- added all the current data in the load file

2024-08-22 12:30 UTC, tamsud commented
Add rxnorm master data as well as in the script

2024-08-23 06:49 UTC, MonishaSivanathan commented
added icd, snomed and rxnorm

2024-08-23 06:58 UTC, tamsud requested changes

2024-08-23 06:58 UTC, tamsud commented on scripts/load_master_data.py
> +        "url" : "https://storage.googleapis.com/ftr/icd10cm/vs/http%3A--hl7.org-fhir-ValueSet-icd-10/tf.5e7b9e0dc05aace8f1a3c8b086556438b0b87848c9304fe9999d8b237e67a8ee.ndjson.gz",
will dict allow duplicate keys?
Have you done testing?

2024-08-23 06:58 UTC, tamsud commented on scripts/load_master_data.py
> +    {"id": "Concept"}
is that necessary to create the concept table?

2024-08-23 07:12 UTC, MonishaSivanathan commented on scripts/load_master_data.py
> +        "url" : "https://storage.googleapis.com/ftr/icd10cm/vs/http%3A--hl7.org-fhir-ValueSet-icd-10/tf.5e7b9e0dc05aace8f1a3c8b086556438b0b87848c9304fe9999d8b237e67a8ee.ndjson.gz",
![Screenshot from 2024-08-23 12-42-24](https://github.com/user-attachments/assets/1cd567b9-5850-4819-832b-f82a165b8683)

2024-08-23 07:13 UTC, MonishaSivanathan commented on scripts/load_master_data.py
> +        "url" : "https://storage.googleapis.com/ftr/icd10cm/vs/http%3A--hl7.org-fhir-ValueSet-icd-10/tf.5e7b9e0dc05aace8f1a3c8b086556438b0b87848c9304fe9999d8b237e67a8ee.ndjson.gz",
i have tested, the data is added

2024-08-23 07:13 UTC, MonishaSivanathan commented on scripts/load_master_data.py
> +    {"id": "Concept"}
ti check the condition alone i have added

2024-08-23 10:45 UTC, tamsud commented
why duplicate keys are there in the dictionary

2024-08-29 07:23 UTC, tamsud approved these changes

2024-08-29 07:23 UTC, merged