Master Table
Ideas2IT/cimpar-backend pull request #8
Opened 2024-06-13 14:40 UTC by MonishaSivanathan

- Added master table for medication
- Added model, controller, router
- Handled Exception and Logger

2024-06-14 07:08 UTC, tamsud requested changes
@MonishaSivanathan Check the given review comments and do the necessary changes

2024-06-14 07:08 UTC, tamsud commented on main.py
> +app.include_router(medication_list_routes.router, tags=["MEDICATION_LIST"])
add a 2 routers.
1. FOR Medication list
2. FOR allergy list

2024-06-14 07:08 UTC, tamsud commented on routes/medication_list_routes.py
> +        logger.info(f"Medication Name:{medication_name}")
In router add a condition to check for the minimum two character. if the length is less than 2 char make it as a response None

2024-06-14 07:08 UTC, tamsud commented on controller/medication_list_controller.py
> +            medication_list = API.make_request(
Add a logger for the response after making the AIDBIX api call

2024-06-14 07:08 UTC, tamsud commented on controller/medication_list_controller.py
> +            medication_list_snomed = API.make_request(
Need allergy list in separate API

2024-06-17 13:05 UTC, MonishaSivanathan commented on routes/medication_list_routes.py
> +        logger.info(f"Medication Name:{medication_name}")
i have updated

2024-06-17 13:06 UTC, MonishaSivanathan commented on controller/medication_list_controller.py
> +            medication_list = API.make_request(
added logger

2024-06-17 13:06 UTC, tamsud approved these changes

2024-06-17 13:06 UTC, merged

2024-06-17 13:07 UTC, MonishaSivanathan commented on routes/master_table_routes.py
> +                logger.info("Allergy name must be at least 2 characters long.")
added

2024-06-17 13:07 UTC, MonishaSivanathan commented on routes/master_table_routes.py
> +        if len(medication_name) < 2:
i have updated