Fix Appointment-bugs
Ideas2IT/cimpar-backend pull request #83
Opened 2024-08-27 14:33 UTC by MonishaSivanathan

- changed the status code as 401 in permission required
- chaned the medical-condition and allergy creation in appointment
- added json response in encounter
- change the regex in patient model

2024-08-27 15:02 UTC, tamsud commented
why are you creating the two different function for saving the single resource (condition/allergy)

2024-08-27 15:02 UTC, tamsud requested changes

2024-08-27 20:25 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +        appointment_result = AllergyIntolerance(
ok and changed

2024-08-27 20:25 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +        response_condition = Condition.make_request(
changed to allergy

2024-08-27 20:25 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +        response_allergy = Condition.make_request(
changed

2024-08-28 05:40 UTC, tamsud requested changes

2024-08-28 05:40 UTC, tamsud commented on controller/appointment_controller.py
> +                    current_condition_app_data = AppointmentClient.create_update_condition(appointment.id, patient_id, app.current_medical_condition, CURRENT)
you have current condition id here why are you not passing it on the function?

2024-08-28 05:40 UTC, tamsud commented on controller/appointment_controller.py
> +                    additional_condition_app_data = AppointmentClient.create_update_condition(appointment.id, patient_id, app.other_medical_condition, OTHER)
why additional_condition.id is not passed to the fucntion?

2024-08-28 05:40 UTC, tamsud commented on controller/appointment_controller.py
> +                    current_allergy_app_data = AppointmentClient.create_update_allergy(appointment.id, patient_id, app.current_allergy, CURRENT)
same here, id is missing?

2024-08-28 05:40 UTC, tamsud commented on controller/appointment_controller.py
> +                    other_allergy_app_data = AppointmentClient.create_update_allergy(appointment.id, patient_id, app.current_allergy, OTHER)
id is missing?

2024-08-28 05:40 UTC, tamsud commented on controller/appointment_controller.py
> +                return allergy_id
- Why are you returning the ID immediately? What's the reason behind it? you always passing a default ID right?
- Why is this check necessary here?
- What would happen if there are multiple appointments for the same patient?

2024-08-28 05:40 UTC, tamsud commented on controller/appointment_controller.py
> +        if condition_id:
- Why are you returning the ID immediately? What's the reason behind it? you always passing a default ID right?
- Why is this check necessary here?
- What would happen if there are multiple appointments for the same patient?

2024-08-28 09:53 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +                    current_condition_app_data = AppointmentClient.create_update_condition(appointment.id, patient_id, app.current_medical_condition, CURRENT)
changed according to the new screen

2024-08-28 09:53 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +                    current_allergy_app_data = AppointmentClient.create_update_allergy(appointment.id, patient_id, app.current_allergy, CURRENT)
changed according to the new screen

2024-08-28 09:53 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +                    other_allergy_app_data = AppointmentClient.create_update_allergy(appointment.id, patient_id, app.current_allergy, OTHER)
changed according to the new screen

2024-08-28 09:54 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +                return allergy_id
changed according to the new screen

2024-08-28 09:54 UTC, MonishaSivanathan commented on controller/appointment_controller.py
> +        if condition_id:
changed according to the new screen

2024-08-28 09:56 UTC, tamsud approved these changes

2024-08-29 06:44 UTC, merged