Master crud
Ideas2IT/cimpar-backend pull request #97
Opened 2024-09-20 10:22 UTC by MonishaSivanathan

- added master crud
- changed values in load_master data script

2024-09-24 07:02 UTC, tamsud requested changes

2024-09-24 07:02 UTC, tamsud commented on scripts/load_master_data.py
>  race_data = [
give the load master data in seperate PR? looks lot of chenages there in data. uanble to verify it

2024-09-24 07:11 UTC, tamsud commented on controller/master_controller.py
> +            lab_test_value = API.make_request(
if display and code:
 logic1
elif code:
 logic2
elif disply:
 logic3

2024-09-24 07:14 UTC, tamsud requested changes

2024-09-24 07:14 UTC, tamsud commented on controller/master_controller.py
> +            lab_test_value = API.make_request(
or else do in tinthis way.
if display and code:
 ?.display$contains={coding.display}&.code$contains={coding.code}
 elif code:
 ?.display$contains={coding.code}
 else display:
 ?.display$contains={coding.display}
 
 append this with the actual string and then call the api.make request

2024-09-24 10:00 UTC, tamsud requested changes

2024-09-24 10:00 UTC, tamsud commented on routes/master_routers.py
> +@router.get("/master/data/{table_name}")
change the url into @router.get("/master/{table_name}/filtered")

2024-09-24 10:14 UTC, MonishaSivanathan commented on controller/master_controller.py
>              for entry in values["entry"]:
added

2024-09-24 10:15 UTC, MonishaSivanathan commented on controller/master_controller.py
> +            values = lab_test_value.json()
added the condition

2024-09-24 10:15 UTC, MonishaSivanathan commented on controller/master_controller.py
> +            lab_test_value = API.make_request(
changed the logic

2024-09-24 10:15 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                return lab_test_value.json()
checked and returned

2024-09-24 10:15 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                    return lab_test_value.json()
checked

2024-09-24 10:16 UTC, MonishaSivanathan commented on controller/master_controller.py
> +            if not master_data:
if the code and display matched it will return already matched, if not matched it will return already exist

2024-09-24 10:17 UTC, MonishaSivanathan commented on controller/master_controller.py
> +
followed

2024-09-24 10:28 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                if not master_data[0]['is_active']:
its checking if te is active colomn is false it will update as false or else it will raise exception

2024-09-24 10:41 UTC, MonishaSivanathan commented on scripts/load_master_data.py
>  race_data = [
gave as seperate PR

2024-09-24 10:41 UTC, MonishaSivanathan commented on controller/master_controller.py
> +            TIME_THRESHOLD = 5
moved to constant file

2024-09-24 10:41 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                master_value = API.make_request(
optimised the code tamil

2024-09-24 10:42 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                    raise Exception("Unable to update")
added the logic

2024-09-24 10:42 UTC, MonishaSivanathan commented on main.py
> +CIMPAR_BE_VERSION = "1.0.13"
i didnt change tamil,now also i took rebase

2024-09-24 10:43 UTC, MonishaSivanathan commented on routes/master_routers.py
> +@router.get("/master/data/{table_name}")
changed tamil

2024-09-25 07:27 UTC, tamsud commented on main.py
> +CIMPAR_BE_VERSION = "1.0.13"
Its not correct why it's comming in ur pr?

2024-09-25 07:28 UTC, tamsud requested changes
Why bumpup commit is there in ur pr?

2024-09-25 10:03 UTC, tamsud approved these changes

2024-09-25 10:04 UTC, merged