Fix - Patient Update
Ideas2IT/cimpar-backend pull request #99
Opened 2024-09-25 13:48 UTC by MonishaSivanathan

- redo the function fetch
- added pagination for get all master

2024-09-26 09:51 UTC, tamsud requested changes

2024-09-26 10:45 UTC, MonishaSivanathan commented on routes/master_routers.py
> +async def get_master_data(table_name: str, request: Request, page: int, page_size: int, code: Optional[str] = "", display: Optional[str] = ""):
changed the limit for both param

2024-09-26 13:05 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                endpoint=f"/{MasterClient.table[table_name]}?_page={page}&_count={page_size}&.display={display}&.code={code}"
nope i have added the contains

2024-09-30 07:23 UTC, tamsud requested changes

2024-09-30 07:30 UTC, MonishaSivanathan commented on controller/master_controller.py
> +                endpoint=f"/{MasterClient.table[table_name]}/?&_page={page}&_count={page_size}&.display$contains={display}&.code$contains={code}"
no its not mandatory
without slash also we can use the API

2024-09-30 12:56 UTC, tamsud approved these changes

2024-09-30 12:57 UTC, merged